geocode:
  cache:
    path: ${GEOCODE_CACHE_PATH:target/geocode-cache}
  geonames:
    url: ${GEOCODE_GEONAMES_URL:https://download.geonames.org/export/dump/cities5000.zip}
    refresh-in-days: ${GEOCODE_GEONAMES_REFRESH_DAYS:7}
    extracted-file-name: cities5000.txt
  maxmind:
    url: ${GEOCODE_MAXMIND_URL:https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz}
    refresh-in-days: ${GEOCODE_MAXMIND_REFRESH_DAYS:7}
    database-file-name: ${GEOCODE_MAXMIND_DATABASE_NAME:GeoLite2-City.mmdb}

management:
  endpoints:
    web:
      exposure:
        include: health
