# This workflow will trigger the remote ssh script to 
# restart application with the latest artefacts version
on: workflow_dispatch
    
name: â–¶ Prod - Restart applications

jobs:
  deploy:
    name: prod-publish-jars
    runs-on: self-hosted

    steps:
      - name: Publish via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: sh /opt/open4goods/bin/publish-jars.sh prod

          
          

                      

                                    
